from django.db import models
from django.conf import settings
import uuid


class FraudReport(models.Model):
    """Manual fraud reports filed by users or generated by the AI scanner."""
    REPORT_STATUS = [
        ('open', 'Open'),
        ('investigating', 'Investigating'),
        ('resolved', 'Resolved'),
        ('dismissed', 'Dismissed'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    property = models.ForeignKey(
        'properties.Property', on_delete=models.CASCADE, related_name='fraud_reports'
    )
    reported_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
        null=True, blank=True, related_name='filed_reports'
    )
    reason = models.TextField()
    status = models.CharField(max_length=20, choices=REPORT_STATUS, default='open')
    admin_notes = models.TextField(blank=True)
    auto_generated = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    resolved_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'fraud_reports'
        ordering = ['-created_at']

    def __str__(self):
        return f'Report: {self.property.title} — {self.status}'
